# This is a basic workflow to help you get started with Actions

name: cfhost Workflow

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 * * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  #  branches: [ "main" ]
    paths-ignore: 
      - '.gitignore'
      - '.github/workflows/test.yml'
  #  - 'dist/**'
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      CF_WORKER_NAME:
        description: 'worker script name for deployment (default take repo variable `CF_WORKER_NAME`)'
        required: false
        default: ''
        type: 'string'
      CF_PAGE_NAME:
        description: 'page project name for deployment (default take repo variable `CF_PAGE_NAME`)'
        required: false
        default: ''
        type: 'string'
      CF_PAGE_BRANCH:
        description: 'page branch for deployment environment, empty or `main` for production env, otherwise for preview (default take repo variable `CF_PAGE_BRANCH`)'
        required: false
        default: ''
        type: 'string'
      deployPage:
        description: 'deploy worker and page (true: worker and page, false: worker)'
        required: false
        default: true
        type: choice
        options:
          - true
          - false
        
  workflow_call:
    inputs:
      proxys: 
        description: 'proxys json data'
        required: true
        type: 'string'
    secrets:
      CF_ACCOUNT_ID:
        required: true
      CF_API_TOKEN:
        required: true
      CF_NAMESPACE_ID:
        required: false
      CF_WORKER_UUID:
        required: false
      CF_PAGE_UUID:
        required: false

env:
  deployPage: ${{inputs.deployPage != 'false'}}
  workerName: ${{inputs.CF_WORKER_NAME || vars.CF_WORKER_NAME}}
  pageName:   ${{inputs.CF_PAGE_NAME || vars.CF_PAGE_NAME}}
  pageBranch: ${{inputs.CF_PAGE_BRANCH || vars.CF_PAGE_BRANCH || 'main'}}
  EVENT_NAME: ${{github.event_name}}
  
  CF_SCRIPT_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/workers/scripts
  CF_SERVICE_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/workers/services
  CF_PROJECT_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/pages/projects
  CF_KV_API: https://api.cloudflare.com/client/v4/accounts/${{secrets.CF_ACCOUNT_ID}}/storage/kv/namespaces/${{secrets.CF_NAMESPACE_ID || vars.CF_NAMESPACE_ID}}/values
  CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
  CF_NAMESPACE_ID: ${{secrets.CF_NAMESPACE_ID || vars.CF_NAMESPACE_ID}}
  CF_WORKER_UUID: ${{secrets.CF_WORKER_UUID}}
  CF_PAGE_UUID: ${{secrets.CF_PAGE_UUID}}
  
  CFHOST: cfhost
  CFHOST_BAK: cfhost_bak
  CFHOST_JSON: cfhost.json
  PROXYS: proxys
  PROXYS_UPDATED: proxys_updated
  PROXYS_JSON: proxys.json
  ENTRY: _worker.js
  UUID: UUID
  KV: KV

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          # https://github.com/orgs/community/discussions/25797#discussioncomment-3249294
          fetch-depth: 0
          
      - id: get-data
        name: get cfhost, merge, backup
        run: |
          [ -z ${{secrets.CF_ACCOUNT_ID}} ] || [ -z $CF_API_TOKEN ] || [ -z $CF_NAMESPACE_ID ] && echo "secrets and CF_NAMESPACE_ID required!" && exit 1;
          merge_backup(){
            local ret=`curl -H "Authorization:Bearer $CF_API_TOKEN" "$CF_KV_API/$1"`
            if echo "$ret"|grep error; then
              grep 'namespace not found' <<< "$ret" && exit 1 || echo "$ret"
            elif [ ! -z "$ret" ] && [ "$ret" != "[]" ]; then
              echo "get-data $1" >> $GITHUB_STEP_SUMMARY
              #curl -X PUT -H "Authorization:Bearer $CF_API_TOKEN" \
              #  -d "" "$CF_KV_API/$1" >> $GITHUB_STEP_SUMMARY
              echo $ret|tr -d '[]'|sed -r 's/, ?/\n/g' > tmp.txt
              
              local bak=`curl -H "Authorization:Bearer $CF_API_TOKEN" "$CF_KV_API/$2"`
              if ! echo "$bak"|grep error && [ ! -z "$bak" ] && [ "$bak" != "[]" ]; then
                echo $bak|tr -d '[]'|sed -r 's/, ?/\n/g' >> tmp.txt
                ret=[$(echo `cat tmp.txt|sort -u`|tr -s ' ' ',')]
                [ "$ret" = "$bak" ] && echo "cfhostChanged=false" >> $GITHUB_ENV;
              fi
              
              echo `cat $3`|tr -d '[]'|sed -r 's/, ?/\n/g' >> tmp.txt
              # cat tmp.txt|sed -r 's/^\s*(.*)/\1/g'
              echo [$(echo `cat tmp.txt|sort -u`|tr -s ' ' ',')] > $3
              curl -X PUT -H "Authorization:Bearer $CF_API_TOKEN" \
                  -d "$ret" "$CF_KV_API/$2" >> $GITHUB_STEP_SUMMARY
              
              #curl -H "Authorization:Bearer $CF_API_TOKEN" $CF_SCRIPT_API/$workerName/content/v2 > s.js
              #local old=`grep -A 1 $3 s.js|grep -v $3|tr -d ' =;'|sed -r 's/^\w+//'`
            fi
          }
          merge_backup $CFHOST $CFHOST_BAK $CFHOST_JSON
          
      - id: check-change
        name: check change of cfhost.json, proxys update time
        env:
          GH_TOKEN: ${{ github.token }}
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.event.after }}
        run: |
          echo "check change.." >> $GITHUB_STEP_SUMMARY
          if [ "$cfhostChanged" = false ]; then
            # ! git diff|grep "$CFHOST_JSON";
            # git config user.name "GitHub Actions Bot"
            # git config user.email "<>"
            # git add $CFHOST_JSON
            # git commit -m "updated cfhost"
            # git push
            echo "cfhost no change" >> $GITHUB_STEP_SUMMARY
            
            [ ! -z '${{ inputs.proxys }}' ] || [ $EVENT_NAME != schedule ] && exit;
            
            # cancel when trigger on schedule # [ -z `git diff --name-only $BEFORE $AFTER 2>&1` ]
            # and when now - (updated time of proxys data) >= 7200s
            #df='+%Y-%m-%d %H:%M:%S %z'
            #s=`curl -H "Authorization:Bearer $CF_API_TOKEN" "$CF_KV_API/$PROXYS_UPDATED"`
            #echo "$ret"|grep error && s=0 || echo "$PROXYS_UPDATED: `date "$df" -d @$s`, now: `date "$df"`" >> $GITHUB_STEP_SUMMARY
            #if [ $((`date +%s` - $s)) -ge 7000 ]; then
              echo "on schedule, no change no need to deploy" >> $GITHUB_STEP_SUMMARY
              gh run cancel ${{ github.run_id }}
              gh run watch ${{ github.run_id }}
            #fi
          fi
          
      - id: get-proxys
        name: get proxys data
        # if: ${{ github.event_name == 'workflow_call' }}
        run: |
          if [ ! -z '${{ inputs.proxys }}' ]; then
            echo '${{ inputs.proxys }}' > $PROXYS_JSON
          else
            ret=`curl -H "Authorization:Bearer $CF_API_TOKEN" "$CF_KV_API/$PROXYS"`
            grep error <<< "$ret" && echo "$ret" || echo "$ret" > $PROXYS_JSON
          fi
          
      - name: setup node
        if: steps.get-proxys.conclusion == 'success'
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: build worker
        run: |
          npm i
          npm run esbuild
          
      - name: deploy worker, page
        env:
          CF_PAGE_ENV: ${{env.pageBranch == 'main' && 'production' || 'preview'}}
        run: bash ./deploy.sh
        
  workflow-keepalive:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1